runtime: python
env: flex
entrypoint: pyagent run -c /app/appdynamics.cfg -- gunicorn -b :$PORT wsgi

beta_settings:
  cloud_sql_instances: somfy-iot:europe-west1:django-db

health_check:
  enable_health_check: False

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10

manual_scaling:
  instances: 1

runtime_config:
  python_version: 2

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.template$
- ^static$

