runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: wsgi.application

libraries:
- name: django
  version: "1.9"
- name: MySQLdb
  version: "1.2.5"
- name: yaml
  version: "latest"
- name: ssl
  version: "2.7.11"

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.template$

